### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by piuccio**
Mainly AWS which released a major(-ish) release

@sihil @adamnfish

### CODE REVIEW

**Comment by sihil** [comment]
This is fine. Am slightly concerned about foisting aws 1.11 on users when there are still unavoidable library clashes (e.g. KCL). But ultimately this can be solved with an exclude on the dependency.

**Comment by piuccio** [comment]
I'll put it this on hold until awslabs/amazon-kinesis-client#75 gets merged

**Comment by piuccio** [comment]
KCL was updated, I can merge if some gives a +1

**Comment by sihil** [comment]
👍

**Pull request merged**
