### PR TITLE
Add google group checker

### PR DESCRIPTION
**Pull request by susiecoleman**
Adding a google group checker to `AuthActions`

@guardian/digital-cms

### CODE REVIEW

**Comment by mbarton** [comment]
Was this removed when we switched to Play 2.6?

**Comment by susiecoleman** [comment]
@mbarton it wasn't removed but `settings` was made private so it's no longer possible to construct a group checker in an app in the same way

**Comment by mbarton** [comment]
Hmm, perhaps we should fix that back to how it was. Does this change allow you to configure the groups it is checking?

**Comment by susiecoleman** [comment]
@mbarton yes. The as the parameters for checking come from a parameterless function that is instantiated when using the `AuthActions` trait. It is also still possible to write essentially the same checker in the fronts code but it's messier than it was previously and I thought given we have a multifactor checker in there the group checker could go in too

**Pull request merged**
